pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                echo 'Компилирам Main.java...'
                bat 'javac src/Main.java'
            }
        }

        stage('Run') {
            steps {
                echo 'Стартирам Main...'
                bat 'java -cp src Main'
            }
        }
    }
}